
services:
  - type: web
    name: louis-realtime-room-web
    runtime: docker
    dockerfilePath: web/Dockerfile
    dockerContext: ./web
    plan: free

  - type: web
    name: louis-realtime-room-api
    runtime: docker
    dockerfilePath: api/Dockerfile
    dockerContext: ./api
    plan: free
