
services:
  - type: web
    name: louis-realtime-room-web
    env: docker
    dockerfilePath: web/Dockerfile
    dockerContext: ./web
    plan: free


  - type: web
    name: louis-realtime-room-api
    env: docker
    dockerfilePath: api/Dockerfile
    dockerContext: ./api
    plan: free
