
services:
  - type: web
    name: louis-realtime-room-api
    runtime: image
    image:
      url: docker.io/coljurten/realroomapi:latest
    plan: free
    envVars:
      - key: PORT
        value: 3001

  - type: web
    name: louis-realtime-room-web
    runtime: image
    image:
      url: docker.io/coljurten/realroomweb:latest
    plan: free
    envVars:
      - key: API_INTERNAL_URL
        fromService:
          type: web
          name: https://louis-realtime-room-api.onrender.com
          property: host
